config/routes.rb
SevranFutsal::Application.routes.draw do
  get "home/index"
  get "clubs/index"
  get "futsal/index"
  get "realisateur/index"

  root 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
	def index
	end
end

app/controllers/futsal_controller.rb
class FutsalController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/realisateur_controller.rb
class RealisateurController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/joueurs_helper.rb
module JoueursHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/futsal/index.html.erb
<div class="well futsal">
<h1>Quelques informations sur le futsal (foot en salle)</h1></br>
</br>
<p> "Depuis 2007, la FFF a mis en place un championnat  de Futsal (Challenge National) composé de deux divisions.
Le Futsal se joue à 5 contre 5 (4 joueurs de champ et un gardien de but).
Le terrain et les buts sont ceux du Hand-Ball et le jeu s'effectue avec un ballon spécifique anti-rebond.
La surface de jeu doit être lisse, dépourvue d'aspérités et non abrasive,  de préférence en bois ou dans un matériau synthétique conformément au réglement de la compétition en question. Les surfaces en béton ou goudronnées sont déconseillées (cf : les lois du jeu du Futsal).
Les matches se disputent en deux mi-temps de 20 ou 25 minutes (temps non effectif).
Il n'y a pas de hors jeu en Futsal."</br>
<div class="text-center">
<iframe width="400" height="225" src="//www.youtube.com/embed/DldSJMjnsEs?rel=0" frameborder="0" allowfullscreen></iframe>
</div>
Contact: </br>
Sevran Futsal United 06 17 97 00 31</br>
Plus d'infos : fff.fr </p>
</div>

app/views/home/index.html.erb
<div class="well intro">
  <p>"Seul le travail paie" est une web-série qui vous plonge au coeur du Sevran Futsal United, situé au quartier des Beaudottes à Sevran (93). Vous allez découvrir une discipline sportive et un univers où l'esprit du sport se mêle à la rage de vaincre et de réussir des joueurs. Comment se finira la saison, joueurs et coachs, ne peuvent le prédire, mais dans leur regard, une seule certitude : Seul le travail paie... </p>

</div>

<div class="row">
  <div class="recit1">
    <div class="col-sm-6 col-md-offset-1 col-md-5 col-md-offset-1 col-lg-offset-1 col-lg-5 col-lg-offset-1">
      <div class="thumbnail">
        <%= image_tag "samba.png" %>
        <div class="caption">
          <h3>Recit 1</h3>
          <p>Plus qu'un club</br>
          Voici deux ans que le club de Sevran Futsal United a été créé. Après une première saison conclue par une montée en division supérieure. Samba Camara, le coach et son assistant Theodore Mendy poursuivent leur travail afin de faire de ce club un modèle sur le terrain et en dehors...</p>
          <p><a class="btn btn-primary" id="b1" role="button">Regarder</a> <a class="btn btn-default" id="r1" role="button">Retour</a></p>
        </div>
      </div>
    </div>
  </div>
    <div id="video1">
      <iframe width="400" height="225" src="//www.youtube.com/embed/4UczzQoMeAA?rel=0" frameborder="0" allowfullscreen></iframe>
    </div>

    <div class="recit2">
      <div class="col-sm-6 col-md-5 col-lg-5">
        <div class="thumbnail">
          <%= image_tag "theo.png" %>
          <div class="caption">
            <h3>Recit 2</h3>
            <p>Une course de fond pour ton Salut</br>
              Théodore Mendy a évolué 15 ans dans le football à onze.A son retour à Sevran après avoir joué en Bretagne, il a le soucis de transmettre aux plus jeunes son expérience. Entre son travail au cimetière et les entrainements, il espère voir éclore plusieurs joueurs au haut niveau...         
            </p>
            <p><a class="btn btn-primary" id="b2" role="button">Regarder</a> <a class="btn btn-default" id="r2" role="button">Retour</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="video2">
    <iframe width="400" height="225" src="//www.youtube.com/embed/cq9Pw47DWYM?rel=0" frameborder="0" allowfullscreen></iframe>
  </div>
</div>

<div class="row">
  <div class="recit3">
    <div class="col-sm-6 col-md-offset-1 col-md-5 col-md-offset-1 col-lg-offset-1 col-lg-5 col-lg-offset-1">
      <div class="thumbnail">
        <%= image_tag "gassama.jpg" %>
        <div class="caption">
          <h3>Recit 3</h3>
          <p>N'essaie pas, fais le</br>
            Souleymane et Gassama. Deux joueurs talentueux mais aussi inséparables. Leur amitié remonte aux bancs de l'école primaire. Pour Théo, celle-ci peut leur jouer des tours quand il faudra faire sa valise et répondre à l'appel du haut niveau. Après avoir été "désorienté" en filière professionnelle, Souleymane parvient à se réorienter en fac d'histoire pour devenir professeur. Gassama, tente sa chance dans un concours d'infirmier. 
          </p>
          <p><a class="btn btn-primary" id="b3" role="button">Regarder</a> <a class="btn btn-default" id="r3" role="button">Retour</a></p>
        </div>
      </div>
    </div>
  </div>

    <div id="video3">
<iframe width="400" height="300" src="//www.youtube.com/embed/MFyOHY7YzWc?rel=0" frameborder="0" allowfullscreen></iframe>
    </div>

    <div class="recit4">
      <div class="col-sm-6 col-md-5 col-lg-5">
        <div class="thumbnail">
          <%= image_tag "otmani.jpg" %>
          <div class="caption">
            <h3>Dans les prochains Récits</h3>
            <p>Vous avez découvert les premiers personnages et le contexte du club.
              Dans les prochains Récits, vous allez découvrir la compétition et la tention qui en découle. Le gymnase Bacquet et les supporters : la "K-soce team", qui mettent le feu lors des matchs.qfqfqfqfqfqq
              Mais aussi, vous allez faire la connaissance du haut niveau avec des joeurs de l'équipe de France : Yassine Mohammed, Moustapha Othmani
              
            </p>
            <p><a class="btn btn-primary" id="b4" role="button">Regarder</a> <a class="btn btn-default" id="r4" role="button">Retour</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="video4">
    <iframe width="400" height="225" src="//www.youtube.com/embed/ctp8zU3YLqc?rel=0" frameborder="0" allowfullscreen></iframe>
  </div>
</div>

app/views/layouts/_footer.html.erb
<hr width=100%>
<div id="footer">
<div class="row">
	<div class="col-xs-offset-1 col-xs-5 col-sm-offset-1 col-sm-5 col-md-offset-1 col-md-5 col-lg-offset-1 col-lg-5">
    <a class="thumbnail part1">
	<%= image_tag "flexi.jpg" %>
    </a>
  <p>Flexi Resto</br>
  	Cuisine du monde</br>
  	27 avenue du général Leclerc
    93270 Sevran, France
    facebook.com/flexiresto.resto
  </p>
</div>
<div class="col-xs-5 col-sm-5 col-md-5 col-lg-5">
    <a class="thumbnail part2">
	<%= image_tag "bootik.jpg" %>
    </a>
  <p>Bootikfoot.com</br>
  	Les services et produits pour l'univers du foot</br>
  </p>
</div>
</div>

app/views/layouts/_header.html.erb
<div class="page-header">
  <h1> Seul le travail paie <small>#Warriors</small></h1>
</div>
<div class="row">
  <div class="btn-group btn-group-justified">
  <div class="btn-group">
    <button type="button" class="btn btn-default btn-club"><%= link_to "Accueil", root_path %></button>
  </div>
  <div class="btn-group">
    <button type="button" class="btn btn-default btn-fut"><%= link_to "Le Futsal", futsal_index_path %></button>
  </div>
  <div class="btn-group">
    <button type="button" class="btn btn-default btn-real"><%= link_to "La réalisation", realisateur_index_path %></button>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seul le travail paie</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Londrina+Outline|Russo+One|Keania+One&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Play' rel='stylesheet' type='text/css'>
  <link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
</head>
<body>
<%= render "layouts/header" %>
<%= yield %>
<%= render "layouts/footer" %>
</body>
</html>

app/views/realisateur/index.html.erb
<div class="panel panel-default aladine">
  <div class="panel-body">
    <p>C'est avec un désir de changement que l'idée de cette série a été pensée il y a un an avec Samba Camara, le coach du club. Après avoir assisté à un entraînement du club, Aladine Zaïane, un jeune web développeur/vidéaste est captivé par l'énergie déployée par l'équipe encadrante et les motivations qui animent le club.
    De plus, le futsal est une activité que beaucoup d'adolescents ont pratiqué mais sans réelles structures. Cette discipline souffre d'ailleurs de ce manque d'organisation. Dans des pays comme l'Espagne ou le Brésil, ce sport est davantage médiatisé. En France, il reste cantonné à un sport de "loisir" pratiqué par des "banlieusards". 
    Pour les besoins de ce pojet et des autres à venir, Aladine monte une boîte de production : La Salle du Temps. Celle-ci a vocation a mêler des projets audiovisuels et l'univers du code informatique qui est une magnifique source de liberté et d'action. Surtout dans les quartiers populaires où il y a un besoin urgent de communication et de professionalisation des structures. Ce projet mêle ainsi, journalisme et empowerment.</br>
    </br>

         Budget : Zero euros !</br>

    Concernant les moyens financiers et matériels pour produire cette web série, il ne faut pas chercher bien loin : ZERO euros, voici le montant de notre budget. La précarité était bien au rendez-vous, les moments de doute nombreux. Mais portés par un idéal et une volonté de fer, le projet est bien là et c'est maintenant à vous de le faire vivre en le partageant avec vos proches.
    </br>

    Aladine Zaïane : Après une licence en sociologie politique, il se lance durant 5 ans dans une sorte de parcours initiatique dans le monde audiovisuel à travers l'association Hors Cadre. Durant ces années il découvre la France en participant à des projets un peu partout dans l'Héxagone, mais aussi le monde. Le Brésil, où il présente un documentaire réalisé par Hors Cadre. Le Moyen-Orient (Egypte, Syrie, Liban, Arabie Saoudite) en 2011, lors des Révolutions arabes, pour rencontrer les acteurs de ces évènements historiques.</br>
    </br>
    La même année, "Rue des cités" lui montre la voie. Ce premier long métrage réalisé par Hakim Zouhani et Carine May, auquel il participa modestement en tant que régisseur est retenu dans la sélection ACID lors du Festival de Cannes 2011. Il sort dans les salles en 2013. On peut aller très loin avec presque rien.</br>
    </br> 
    Enfin, il ponctue son initiation par une formation intensive au code informatique à Simplon.co. D'autres projets vont suivre à la suite de cette formation, dans le domaine des applications mobiles en lien direct (et toujours) avec les structures des quartiers populaires. </br>
    Pour contacter Aladine Zaïane : 06 68 90 84 52
    </p>
  </div>
</div>